### ISSUE TITLE
Server crashes if parallel run concurrency test

### ISSUE THREAD

**Issue by saygoodbyye** [duckdb/pg_duckdb#348]
### What happens?

If we parallel run concurrency test added in #310, server will crash
PostgreSQL build:
```
CFLAGS='-Og' ./configure --enable-tap-tests --with-openssl --enable-debug --enable-cassert --with-icu --with-lz4 --with-libxml
``` 

### To Reproduce

Patch test/regression/schedule:
```
test: concurrency concurrency concurrency concurrency
```
Then execute
```
make check
```
regression.out:
```
# parallel group (4 tests): concurrency concurrency concurrency concurrency
not ok 1     + concurrency                               656 ms
# (test process exited with exit code 2)
not ok 2     + concurrency                               519 ms
# (test process exited with exit code 2)
not ok 3     + concurrency                               520 ms
# (test process exited with exit code 2)
not ok 4     + concurrency                               512 ms
# (test process exited with exit code 2)
```
backtrace:
```c
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007579ef24526e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007579ef2288ff in __GI_abort () at ./stdlib/abort.c:79
#5  0x000063f7da08a82a in ExceptionalCondition (conditionName=<optimized out>, fileName=<optimized out>, lineNumber=373) at assert.c:66
#6  0x00007579efee3035 in BufferGetBlock (buffer=<optimized out>) at /tmp/pgsql/include/server/storage/bufmgr.h:373
#7  BufferGetPage (buffer=<optimized out>) at /tmp/pgsql/include/server/storage/bufmgr.h:406
#8  pgduckdb::HeapReader::ReadPageTuples (this=0x7579cc000d70, output=...) at src/scan/heap_reader.cpp:89
#9  0x00007579efee577d in pgduckdb::PostgresSeqScanFunction::PostgresSeqScanFunc (context=..., data=..., output=...) at src/scan/postgres_seq_scan.cpp:97
#10 0x00007579ebbbc49e in duckdb::PhysicalTableScan::GetData(duckdb::ExecutionContext&, duckdb::DataChunk&, duckdb::OperatorSourceInput&) const () from /tmp/pgsql/lib/libduckdb.so
#11 0x00007579ebd60a0f in duckdb::PipelineExecutor::FetchFromSource(duckdb::DataChunk&) () from /tmp/pgsql/lib/libduckdb.so
#12 0x00007579ebd6bfe9 in duckdb::PipelineExecutor::Execute(unsigned long) () from /tmp/pgsql/lib/libduckdb.so
#13 0x00007579ebd6c352 in duckdb::PipelineTask::ExecuteTask(duckdb::TaskExecutionMode) () from /tmp/pgsql/lib/libduckdb.so
#14 0x00007579ebd6258d in duckdb::ExecutorTask::Execute(duckdb::TaskExecutionMode) () from /tmp/pgsql/lib/libduckdb.so
#15 0x00007579ebd6b04b in duckdb::TaskScheduler::ExecuteForever(std::atomic<bool>*) () from /tmp/pgsql/lib/libduckdb.so
#16 0x00007579eeeecdb4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#17 0x00007579ef29ca94 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#18 0x00007579ef329c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```
Maybe this test case will not fail by the first try. 

Edited: You can get the same thing If execute materialized_view test instead of concurrency test.

### OS:

Ubuntu 24.04

### pg_duckdb Version:

master

### Postgres Version:

REL_17_STABLE

### Full Name:

Egor Chindyaskin

### Affiliation:

Postgres Professional

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [ ] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

**Comment by mkaruza** [comment]
Should be fixed with #351
